## gen_data.nim — build tool (runs under regular Nim, NOT nimony).
##
##   nim r tools/gen_data.nim
##
## Reads the MDN CSS data under data/*.json and emits src/css/data.nim as a set
## of compact, std/json-free string blobs. Downstream nimony code parses these
## blobs with a tiny hand-rolled splitter (see data_load.nim) — so no module in
## the shipped library depends on std/json, which keeps nimony compiles cheap.
##
## Blob format: entries separated by '\n', fields within an entry by '\t'.
## (CSS value-definition syntax never contains tab or newline, so this is safe.)
##
## To track a CSS-spec change: replace data/*.json and re-run this tool.

import std/[json, os, strutils, tables, algorithm]

const here = currentSourcePath().parentDir
const dataDir = here / ".." / "data"
const outFile = here / ".." / "data.aowl"

proc load(name: string): JsonNode =
  parseFile(dataDir / name & ".json")

## unit dimension buckets, derived from the MDN "groups" tags.
proc unitDimension(groups: seq[string]): string =
  for g in groups:
    case g
    of "CSS Lengths": return "length"
    of "CSS Angles": return "angle"
    of "CSS Times": return "time"
    of "CSS Frequencies": return "frequency"
    of "CSS Resolutions": return "resolution"
    of "CSS Flexible Lengths": return "flex"
    else: discard
  "other"

proc emit(entries: seq[(string, string)]): string =
  ## Join (key,val) pairs into a "key\tval\n…" blob, sorted by key for
  ## deterministic output (so regenerating produces a clean diff).
  var e = entries
  e.sort(proc (a, b: (string, string)): int = cmp(a[0], b[0]))
  var parts: seq[string]
  for (k, v) in e:
    # VDS whitespace is insignificant — collapse tabs/newlines so they can't
    # collide with our field/record delimiters.
    let vv = v.replace('\t', ' ').replace('\n', ' ').replace("  ", " ").strip()
    doAssert '\t' notin k and '\n' notin k, "delimiter clash in key: " & k
    parts.add k & "\t" & vv
  parts.join("\n")

when isMainModule:
  # properties: name -> value-definition syntax
  var props: seq[(string, string)]
  for name, body in load("properties").pairs:
    if body.hasKey("syntax"):
      props.add (name, body["syntax"].getStr)

  # syntaxes: <name> -> value-definition syntax
  var synt: seq[(string, string)]
  for name, body in load("syntaxes").pairs:
    if body.hasKey("syntax"):
      synt.add (name, body["syntax"].getStr)

  # basic data types: just the set of names (angle, color, length, …)
  var types: seq[(string, string)]
  for name, _ in load("types").pairs:
    types.add (name, "")

  # units: unit -> dimension bucket
  var units: seq[(string, string)]
  for name, body in load("units").pairs:
    var groups: seq[string]
    if body.hasKey("groups"):
      for g in body["groups"]: groups.add g.getStr
    units.add (name, unitDimension(groups))

  # at-rules: @name -> syntax
  var atrules: seq[(string, string)]
  for name, body in load("at-rules").pairs:
    atrules.add (name, (if body.hasKey("syntax"): body["syntax"].getStr else: ""))

  # selectors: split the pseudo-classes / pseudo-elements out of the concept list.
  # Key = bare name (no leading colons, no trailing "()"); val = "1" if functional.
  proc pseudoName(k: string): (string, bool) =
    var s = k
    while s.len > 0 and s[0] == ':': s = s[1 .. ^1]
    var fn = false
    if s.endsWith("()"): s = s[0 .. ^3]; fn = true
    (s, fn)
  var pclasses: seq[(string, string)]
  var pelements: seq[(string, string)]
  for name, _ in load("selectors").pairs:
    if name.startsWith("::"):
      let (n, fn) = pseudoName(name)
      if n.len > 0: pelements.add (n, (if fn: "1" else: ""))
    elif name.startsWith(":"):
      let (n, fn) = pseudoName(name)
      if n.len > 0: pclasses.add (n, (if fn: "1" else: ""))

  var o = """## GENERATED by tools/gen_data.nim from mdn-data css. DO NOT EDIT.
## Regenerate after editing data/*.json:  nim r tools/gen_data.nim
##
## Compact, std/json-free tables. Entries are '\n'-separated, fields '\t'-separated.
## Parse them with the helpers in data_load.nim.

"""
  o.add "const cssPropertyBlob* = " & escape(emit(props)) & "\n\n"
  o.add "const cssSyntaxBlob* = " & escape(emit(synt)) & "\n\n"
  o.add "const cssTypeBlob* = " & escape(emit(types)) & "\n\n"
  o.add "const cssUnitBlob* = " & escape(emit(units)) & "\n\n"
  o.add "const cssAtRuleBlob* = " & escape(emit(atrules)) & "\n\n"
  o.add "const cssPseudoClassBlob* = " & escape(emit(pclasses)) & "\n\n"
  o.add "const cssPseudoElementBlob* = " & escape(emit(pelements)) & "\n"

  writeFile(outFile, o)
  echo "wrote ", outFile
  echo "  properties:      ", props.len
  echo "  syntaxes:        ", synt.len
  echo "  types:           ", types.len
  echo "  units:           ", units.len
  echo "  at-rules:        ", atrules.len
  echo "  pseudo-classes:  ", pclasses.len
  echo "  pseudo-elements: ", pelements.len
